import os

RECRUIT_API_KEY = os.getenv('RECRUIT_API_KEY')

MARIADB_USER = os.getenv('MARIADB_USER')
MARIADB_PASSWORD = os.getenv('MARIADB_PASSWORD')
MARIADB_HOST = os.getenv('MARIADB_HOST')
MARIADB_DB_NAME = os.getenv('MARIADB_DATABASE')
